server:
  port: 8080

spring:
  application:
    name: notes-manager

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/notes_manager}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true